### ISSUE TITLE
Fails to compile on kernel 6.5.x

### ISSUE THREAD

**Issue by brndd** [sihawken/i915-sriov-kmod#2]
Hey, just a heads up that you should rebuild this with the latest upstream changes from https://github.com/strongtz/i915-sriov-dkms to fix compilation on latest kernels.

I successfully set up a SR-IOV passthrough with Looking Glass on my 12900k using this kmod, so thanks for that!

**Comment by sihawken** [comment]
I just triggered a rebuild of the copr repository, so it should work now with the upstream changes!

**Comment by sihawken** [comment]
I created a mirror of the dkms library which should automatically pull any changes, and then rebuild it on the copr repository. Any further upstream changes should be automatically updated.
